import = [
  "~/.config/alacritty/tokyonight.toml",
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
padding.x = 0
padding.y = 0
dynamic_padding = true
dynamic_title = true
option_as_alt = "Both"

[font]
normal.family = "CommitMono Nerd Font"
bold.family = "CommitMono Nerd Font"
italic.family = "CommitMono Nerd Font"
bold_italic.family = "CommitMono Nerd Font"

#normal.family = "Hack Nerd Font"
#bold.family = "Hack Nerd Font"
#italic.family = "Hack Nerd Font"
#bold_italic.family = "Hack Nerd Font"
offset.x = 0
offset.y = 0
size = 12
builtin_box_drawing = true 

[cursor]
style = "beam"

[keyboard]
bindings = [
{ key = "+", mods = "Control", action = "IncreaseFontSize" },
{ key = "-", mods = "Control", action = "DecreaseFontSize" },
{ key = "=", mods = "Control", action = "ResetFontSize" },
]
