import = [
"~/.config/alacritty/tokyonight.toml",
]
[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font"

size = 12
