theme = "Tokyo Night"
default_source = "Nyaa"
download_client = "Transmission"
timeout = 30
scroll_padding = 3
cursor_padding = 4
save_config_on_change = true
hot_reload_config = true

[client.command]
cmd = 'curl "{torrent}" > ~/{file}'
shell_cmd = "sh -c"

[client.transmission]
base_url = "http://localhost:9091/transmission/rpc"
username = "bosse"
password_file = "/home/bosse/Documents/obsidian-vault/05 - Permanent/transmission-password.md"
use_magnet = true
paused = false
peer_limit = 100
download_dir = "/home/bosse/Videos/Anime/"
bandwidth_priority = "Low"

[source.nyaa]
base_url = "https://nyaa.si/"
default_sort = "Date"
default_sort_dir = "Desc"
default_filter = "NoFilter"
default_category = "AllCategories"
default_search = ""
rss = false

[source.nyaa.columns]
category = true
title = true
size = true
date = true
seeders = true
leechers = true
downloads = true

[source.sukebei]
base_url = "https://sukebei.nyaa.si/"
default_sort = "Date"
default_sort_dir = "Desc"
default_filter = "NoFilter"
default_category = "AllCategories"
default_search = ""
rss = false

[source.sukebei.columns]
category = true
title = true
size = true
date = true
seeders = true
leechers = true
downloads = true

[source.torrentgalaxy]
base_url = "https://tgx.sb/"
default_sort = "Date"
default_sort_dir = "Desc"
default_filter = "NoFilter"
default_category = "AllCategories"
default_search = ""

[source.torrentgalaxy.columns]
category = true
language = true
title = true
imdb = true
uploader = true
size = true
date = true
seeders = true
leechers = true
views = true
