preload = /home/bosse/Pictures/Wallpapers/sunset-waterfall-scenery-digital-art-4k-wallpaper-uhdpaper.com-224@1@n.jpg
wallpaper = DP-3, /home/bosse/Pictures/Wallpapers/sunset-waterfall-scenery-digital-art-4k-wallpaper-uhdpaper.com-224@1@n.jpg
splash = false
ipc = off
