preload = /home/bosse/Pictures/Wallpapers/a_black_background_with_purple_and_blue_spots.png
wallpaper = DP-3, /home/bosse/Pictures/Wallpapers/a_black_background_with_purple_and_blue_spots.png
splash = false
ipc = off
