[general]
import = [
  "~/.config/alacritty/tokyonight.toml",
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
padding.x = 0
padding.y = 0
dynamic_padding = true
dynamic_title = true
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font"
bold.family = "MesloLGS Nerd Font"
italic.family = "MesloLGS Nerd Font"
bold_italic.family = "MesloLGS Nerd Font"

offset.x = 0
offset.y = 0
size = 12
builtin_box_drawing = true

[cursor]
style = "block"

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
  { key = "+", mods = "Control", action = "IncreaseFontSize" },
  { key = "-", mods = "Control", action = "DecreaseFontSize" },
  { key = "=", mods = "Control", action = "ResetFontSize" },
]
