name = "Tokyo Night"
bg = "Reset"
fg = "White"
border = "Rounded"
border_color = "Blue"
border_focused_color = "Cyan"
hl_bg = "#292e42"
solid_bg = "White"
solid_fg = "Black"
success = "Green"
error = "Red"
info = "Green"
warning = "Yellow"
